### ISSUE TITLE
Kubos 1.0 [Milestone 1]

### ISSUE THREAD

**Issue by davesims** [kubostech/kubos#32]
* Telemetry
  - [x] Telemetry/Pub/Sub: Refactoring & Testing integration [KUBOS-277](https://kubostech.atlassian.net/browse/KUBOS-277)
  - [x] Pub/Sub: Make subscribers dynamic [KUBOS-272](https://kubostech.atlassian.net/browse/KUBOS-272)
  - [x] Pub/Sub: Make topic subscription dynamic [KUBOS-271](https://kubostech.atlassian.net/browse/KUBOS-271)
  - [ ] Linux Telemetry: Inter-process Communication [KUBOS-350](https://kubostech.atlassian.net/browse/KUBOS-350)
  - [ ] Linux Telemetry: Logging Refactor RTOS (uKub) logging into main repo [KUBOS-280](https://kubostech.atlassian.net/browse/KUBOS-280)
  - [x] Linux Telemetry: Logging integration [KUBOS-207](https://kubostech.atlassian.net/browse/KUBOS-207)
  - [x] Linux Telemetry: Build a Kubos service [KUBOS-281](https://kubostech.atlassian.net/browse/KUBOS-281)
  - [x] Linux Telemetry: Build a Kubos user application [KUBOS-282](https://kubostech.atlassian.net/browse/KUBOS-282)
  - [ ] Linux Telemetry - Create the Kubos Linux Telemetry Service [KUBOS-283](https://kubostech.atlassian.net/browse/KUBOS-283)
* SDK/Tooling
  - [x] Kubox Linux Tooling: Flash utility
  - [x] Kubos Linux Tooling: Toolchain(s)
    * ~~TODO: Need to know how/when the OS and lower-level files will be loaded onto the board? When someone orders an OBC and wants kubos-linux, what does that process look like?~~ Question answered, the kernel will be loaded.
  - [x] Kubos Linux Tooling: Target [KUBOS-334](https://kubostech.atlassian.net/browse/KUBOS-334)
  - [ ] Kubos-cli updated interface to work with Linux
    - [x] Kubos-cli: Create a user application [KUBOS-330](https://kubostech.atlassian.net/browse/KUBOS-330)
    - [x] Kubos-cli: Upload a user application [KUBOS-335](https://kubostech.atlassian.net/browse/KUBOS-335)
    - [ ] Kubos-cli: Debug a user application [KUBOS-329](https://kubostech.atlassian.net/browse/KUBOS-329) 
  - [x] Misc Packaging (Unknowns on SDK administration, TBD)
* Final Release Process
  - [ ] Documentation (Unknowns: TBD)
    - [ ] Kubos-cli: Improve and complete documentation [KUBOS-198](https://kubostech.atlassian.net/browse/KUBOS-198)
  - [ ] Vagrant image published to Atlas
  - [ ] kubos-cli to PyPi
  - [ ] Integration/Manual QA/Testing (Unknowns: TBD)
  - [ ] Integrate Jenkins/GitHub/CI/CD
