### ISSUE TITLE
Milestone 1 Current Doc Audit

### ISSUE THREAD

**Issue by CatFreed** [kubostech/kubos#39]
Things that could be changed to make the docs better for milestone 1:

- [ ] kubos
	- [ ] changelog
		- [ ] Update it :P
	- [ ] main.md
		- [ ] Update all product names to be consistent
			- [ ] Kubos SDK
			- [ ] Kubos CLI
			- [ ] KubOS Linux
			- [ ] KubOS RT
		- [ ] Update file names to be consistent
			- [ ] hypens, not underscores
			- [ ] constistent casing
		- [ ] Move 'contributing' to by changelog (not a sub-document)
		- [ ] Add API link for telemetry
		- [ ] should telemetry-aggregator and ipc also be exposed?
		- [ ] "Installing CLI" - [ ] misleading.  it's also installing vagrant.  Should probably still be "Installing SDK"
		- [ ] "Upgrading CLI" -> Upgrading SDK or Upgrading SDK components
	- [ ] contribution-process
		- [ ] Update 'create a jira issue'
			for stories: follow standard 'as a [user]' format
			mention linking to epics
		- [ ] Change 'create personal copy'
			we're making branches against master now
		- [ ] create a pull request
			verify instructions still accurate
			mention tagging people for review
			mention WIP tag
		- [ ] add 'JIRA -> Reviewing' blurb for stories waiting for PR approval
	- [ ] cli-installing - [ ] Misnomer.  Really, installing sdk
		- [ ] Fix 'kubos-sdk'
		- [ ] update vagrant box name
		- [ ] Typo: "current Directory"
		- [ ] "It is strongly recommended" - [ ] need handholding for this
		- [ ] Mounting synced folders - [ ] update instructions.  No example line currently exists
		- [ ] Missing 'vagrant up' line
		- [ ] A link to the upgrading doc might be nice
	- [ ] cli-upgrading
		- [ ] Kubos -> KubOS
		- [ ] Fix naming (kubos-cli -> KubOS CLI)
		- [ ] Add 'to check which version of cli, use `kubos version`'
		- [ ] Typo: "avaialble"
		- [ ] sudo kubos update -> kubos update
		- [ ] add blurb about `kubos use`
		- [ ] Add section about downgrading each component (or stick in a different doc)
		- [ ] A link to the install doc might be nice
	- [ ] first-project
		- [ ] fix naming
		- [ ] update vagrant box name
		- [ ] Repeat of shared folder note: handholding.  Alternatively, remove this section, since it's not really related to building your first test project.
			- [ ] also, is this still the recommended practice?  How do you do `kubos init` on the host machine?  b/c you can't do `kubos init` on a folder that already exists...
		- [ ] Add link for example linux project
	- [ ] cli-reference
		- [ ] Add links at the top to each section
		- [ ] An overview section with all of the kubos commands and the quick description at the top could be nice.  basically just copy paste the output of `kubos --help`, or make a pretty table.
		- [ ] Possibly re-org.  Most command references are ordered by command, not by function.
			- [ ] If not re-org, then the doc should be renamed.  SDK Process Overview, or something...
		- [ ] go into way more detail on all the things.
		- [ ] Make sure all kubos commands and all their options are documented here.
		- [ ] "Yotta needs" -> "KubOS CLI needs"
		- [ ] "kubos build -- [ ] -v" - [ ] what's the '--' for?
		*** Kubos linking description/instructions could probable use some going over.
		- [ ] is there a script for linking everything now?
		- [ ] 'TODO' do the thing.
	*** A troubleshooting/FAQ doc could be good.
	- [ ] kubos-development.md
		- [ ] Fix naming
		- [ ] Expand intro blurb with overview of development process.  "If you want to make changes to the Kubos code, perhaps for debugging purposes, you'll need to clone the kubos repo and then link the changed modules to your kubos sdk project" - or something to that effect.
		- [ ] Getting started - [ ] "Modifying an existing Kubos module" doesn't make sense for the text that follows
		- [ ] Since it's recommended to use external shared folders, it might be good to give the process for cloning kubos externally
		and then linking it in the Vagrantfile and running 'vagrant reload''
		- [ ] 'Yotta' - [ ] Make hyperlink to yotta docs
		- [ ] Linking in a local module - [ ] make example directory an actual directory.
			- [ ] "Let's say you want to add debug lines to {module}..." - [ ] Use actual module path.
		- [ ] Change /home/kubos/example to /home/kubos/<project_name> to match previous example `kubos init`
		- [ ] Add instructions for how to unlink modules?
	- [ ] MSP430-launchpad-guide
		- [ ] Fix naming
		- [ ] Update kubos doc links to match formatting of other docs.  "docs/[doc]"
		- [ ] Flashing the board - update the USB passthrough description.  Vagrant should be doing it now.
		- [ ] "sudo kubos flash" - is the sudo still required?
	- [ ] STM32F4-discovery-board-guide
		- [ ] Fix naming
		- [ ] Fix doc URLs for consistency
		- [ ] Fix "sudo kubos flash"?
	- [ ] Linux_Overview
		- [ ] change file name. underscores->hyphen.  Add 'kubos'
		- [ ] Linux -> KubOS Linux
		- [ ] Update busybox commands list
	- [ ] Linux_on_iobc
		- [ ] change file name. underscores->hyphen.  Add 'kubos'
		- [ ] Better highlight that this is a doc specifically for the bootloaders and kernel, not user applications.  Should only be needed if the kernel is not pre-loaded onto the board, or if the kernel needs to be manually updated for some reason.
	- [ ]  User_App_on_iOBC
		- [ ] change file name.
		- [ ] change "KubOS Documentation" -> "Kubos Documentation", since the SDK is lower case, we're just referring to the company's documentation.
		- [ ] Fix zModem file selector example formatting
		- [ ] Example - Add command to exit minicom at very end
	
kubos-co
	*** Developer notes for working with/updating vagrant and the cli could be good
	*** Standards doc - naming, coding, etc
