### ISSUE TITLE
Kubos 1.0 [Milestone 2]

### ISSUE THREAD

**Issue by davesims** [kubostech/kubos#50]
###  Milestone 2
- [x] Kernel Update
- [x] Userland/app Update
- [x] Root FS
- [x] Command & Control Framework
- [x] ~~Build Info Command~~ Kicking out to next release
- [x] Noop
- [ ] CSP (stretch) - CSP Commands for C&C
- [ ] GDB (stretch) - Turn on GDB for ISIS board

**Comment by davesims** [comment]
Note: Remote update for this release tracked in https://github.com/kubostech/kubos/issues/54
