### ISSUE TITLE
Kubos 1.0 [Milestone vRemoteUpdate]

### ISSUE THREAD

**Issue by CatFreed** [kubostech/kubos#54]
Milestone 3 (not currently prioritized):
- [ ] remote update from U-Boot (outside file transfer. in case of completely corrupt linux) - nice
- [ ] create kpack-base.itb (for rollback) - [KUBOS-401](https://kubostech.atlassian.net/browse/KUBOS-401)
- [ ] Abstract fw_setenv (C&C) - nice
	- [ ] interactive 'select version' menu?
- [ ] Rootfs overlay - nice
	- [ ] Note: This affects rollback...how do you rollback a single file?
- [x] kpack for NOR flash files - [KUBOS-395](https://kubostech.atlassian.net/browse/KUBOS-395)
- [ ] Remote Update Verification
	- [x] kernel (.itb)
		- [x] checking methods (curr crc+sha1) - [KUBOS-403](https://kubostech.atlassian.net/browse/KUBOS-403)
		- ~~[ ] add signature? (U-Boot 'verified boot options') - doubt it~~
	- [ ] User app
		- [ ] built in unit tests - nice
- [ ] System recovery
	- [x] UBoot: Failed upgrade counter - [KUBOS-323](https://kubostech.atlassian.net/browse/KUBOS-323)
	- [x] UBoot: failed linux boots counter - [KUBOS-404](https://kubostech.atlassian.net/browse/KUBOS-404)
        - [x] UBoot: Ultra-fail boot into ISIS RT - [KUBOS-405](https://kubostech.atlassian.net/browse/KUBOS-401)
        - [ ] UBoot: Ultra-fail boot into KubOS RT - nice
-------------------------------------------------------------------------

Milestone 2:
- [ ] SDK
  - [x] Upload non-application files (ex. scripts) [KUBOS-313](https://kubostech.atlassian.net/browse/KUBOS-313)
  - [x] Upload kubos update package (kpack) [KUBOS-325](https://kubostech.atlassian.net/browse/KUBOS-325)
  - [x] Add config.json options for controlling user app init scripts
    - [x] TODO: Review [KUBOS-340](https://kubostech.atlassian.net/browse/KUBOS-340) and settle on workflow
  - [ ] MAYBE: `kubos debug` for linux [KUBOS-339](https://kubostech.atlassian.net/browse/KUBOS-339)
- [x] SDK Flash progress bar (scrape minicom)
- [x] Linux
  - [x] Implement 'reboot-into-system-update-mode' option? (or just let uboot detect new files and act accordingly)
  - [x] Kernel versioning [KUBOS-324](https://kubostech.atlassian.net/browse/KUBOS-324)
  - [x] Separate current rootfs partition into read-only rootfs and read-write persistent (user) data partitions (and set up symlinks(?) for ease-of-use)
- [x] U-Boot
  - [x] Detect presence of new upgrade package [KUBOS-322](https://kubostech.atlassian.net/browse/KUBOS-322)
- ~~[ ] Automation~~
  - ~~[ ] Kernel update [KUBOS-327](https://kubostech.atlassian.net/browse/KUBOS-327)~~
- [x] Documentation
  - [x] Kernel update [KUBOS-326](https://kubostech.atlassian.net/browse/KUBOS-326)

-------------------------------------

- [x] Questions
  - [x] Are we including error handling and/or systems recovery in this? *Nope*
  - [x] Are we including authentication/validation in this? *Nope*
  - [x] How will the new kernel be loaded?
    - [x] SDK transfer to where on board? *New partition*
    - [x] How to indicate new file?
  - [x] Do we want user apps from `kubos flash` to be automatically started after transfer?
  - [x] How should the system be rebooted after receiving a new kernel file?  *For now, manually*
    - SDK (or other external) command to trigger reboot?
    - Automatically?  Immediately vs scheduled?
  - [x] How to handle device tree updates? (*.dtb)  **In theory** we should never need to add devices on the fly, but in practice... *Same way as the other update package files.  Just to NOR instead of SD partition*
  - [x] Also, uboot env updates?  *Should follow the same logic as .dtb, since they both live in NOR flash and are involved in similar areas of the boot process.*
  - [x] Package manager? (RPM, dpkg, etc) *Not right now*

**Comment by davesims** [comment]
Just wanted to ✨ this. Thanks @CatFreed.

**Comment by CatFreed** [comment]
The vast majority of features have been implemented and all remaining work is contained in JIRA stories. Closing this issue since it has become stale.
