### ISSUE TITLE
C Style Guide/Linter

### ISSUE THREAD

**Issue by davesims** [kubostech/kubos#72]
### C Style for Kubos

Let's finish the conversation about C style at Kubos here.

#### TODO:
- [ ] Decide on a style guide (Google, AT&T, etc.)
- [ ] Document in the repo
- [ ] Find a linter & integrate into CI.

/cc @kubostech/devs

**Comment by CatFreed** [comment]
Wrote our own, located in our [standards doc](https://github.com/kubostech/kubos/blob/master/docs/kubos-standards.md).
There is also a file, [.clang-format](https://github.com/kubostech/kubos/blob/master/.clang-format), which can be used to automatically format the code.

Haven't done any research into a linter for CI.
