### ISSUE TITLE
1.0 Release Checklist

### ISSUE THREAD

**Issue by davesims** [kubostech/kubos#82]
## Kubos Repo
 - [x] Ensure all PR’s Have been Merged (That are going to ship in the new release).
 - [x] Push Kubos Changelog. 
 - [x] Verify Kubos repo Circle Test Pass (Building all Example projects)
 - [x] Generate Doxygen Docs
 - [x] Review Docs before publishing to docs.kubos.co. Fix bugs as needed.
 - [x] Publish docs to docs.kubos.co
 - [x] Tag with the new version number and push the tag to Kubos Repo

## Kubos-CLI
 - [x] If you want the CLI to have a version number update the module.json file in the kubostech/kubos-cli root directory with the desired version
 - [x] Merge all the desired feature PR's for this release to Master
 - [x] If the Circle builds passed 💥  You're automagically released :shipit: 

### Automation Script:
 - [ ]  cd Into the kubos-vagrant/builder/ directory in the kubos-vagrant repo
 - [ ] To provision, test, upload and release a box boxes run `./main.py --all <box_name> <version_number>
 - [ ] To provision and release both boxes use the box name “all”

**Comment by davesims** [comment]
@kyleparrott @CatFreed @plauche @jacoffey3 Is this checklist still up to date?

**Comment by kyleparrott** [comment]
I've updated the CLI release process to reflect all of the CI/CD changes since the creation of this list.

**Comment by davesims** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release v1.0 - Kubos Repo](https://trello.com/c/SFLz3WUk/4-release-v10-kubos-repo)
