### ISSUE TITLE
0.2.2 Release Checklist

### ISSUE THREAD

**Issue by plauche** [kubostech/kubos#90]
## Kubos Repo
 - [x] Ensure all PR’s Have been Merged (That are going to ship in the new release).
 - [x] Push Kubos Changelog. 
 - [x] Verify Kubos repo Circle Test Pass (Building all Example projects)
 - [x] Generate & Publish Doxygen Docs
 - [x] Review Docs and Fix bugs as needed.
 - [x] Tag with the new version number and push the tag to Kubos Repo

## Kubos-CLI
 - [ ] Note: CD will soon be implemented so this is a temporary process.
 - [x] Ensure all PR’s have merged and integration tests have passed. (Building all example projects.)
 - [x] Tag the latest commit with the new version. Push to origin
 - [x] Run `python setup.py bdist_wheel --universal`
 - [x] After building run  `twine upload dist/*`

### Automation Script:
 - [x]  cd Into the kubos-vagrant/builder/ directory in the kubos-vagrant repo
 - [x] To provision, test, upload and release a box boxes run `./main.py --all <box_name> <version_number>
 - [x] To provision and release both boxes use the box name “all”

**Comment by kyleparrott** [comment]
Since the release has been completed successfully and no major flaws were found in this process I am closing this issue.
